'use strict';
const $=s=>document.querySelector(s);
let deposits=[],lastQuote=-1,pending=null,opened=false,previousFocus=null,toastTimer,videoBlob=null,videoURL=null,stream=null,recorder=null,recordTimer=null,recordTick=null,recordingRequest=0,recordFinalizing=false,profile=null,inviteLink=null,inviteSignature='',submitting=false;
const inviteToken=location.pathname.startsWith('/ask/')?location.pathname.split('/')[2]:null;
let previewMode=!inviteToken,submissionId=crypto.randomUUID();
const questions=['最近有點低潮，可以跟我說一個我的優點嗎？','你覺得我做哪件事的時候看起來最有魅力？'];let question=questions[0];
const starterQuotes=[{author:'自信銀行 · 體驗卡',text:'今天還願意往前走一點點的你，已經很不容易了。'},{author:'自信銀行 · 體驗卡',text:'你不需要每一刻都很有自信，才能值得被喜歡。'},{author:'自信銀行 · 體驗卡',text:'先休息一下也可以。你的價值，不會因為今天的狀態而減少。'}];
const all=()=>deposits;
function promptSignIn(){openModal('modal-signin');}
function renderGuest(count=0){$('#account-name').textContent='先逛逛，不用急著登入';$('#account-action').textContent='已有存摺？';$('#account-action').href='/signin-with-chatgpt?return_to=%2Fbank';$('#connection-state').textContent='先收集心意，開箱時再登入就好。';$('#bank-privacy-note').textContent='還沒登入也能邀請朋友。請用同一個瀏覽器回來開箱，登入後就能跨裝置保存。';$('#deposit-list').replaceChildren();const card=document.createElement('article');card.className='deposit-card';const p=document.createElement('p');p.textContent=count?`已有 ${count} 份心意等你拆開。登入後，它們就會收進你的私人存摺。`:'先抽一張溫暖的體驗卡，或邀請朋友存入第一份心意。';card.append(p);if(count){const b=document.createElement('button');b.textContent='🎁 開箱我的心意';b.className='extra-button w-full';b.onclick=promptSignIn;card.append(b);}$('#deposit-list').append(card);document.querySelectorAll('[data-count]').forEach(e=>e.textContent=count);$('#notification-count').textContent=count;$('#notification-count').hidden=!count;}
async function refreshGuest(){try{const state=await api('me');if(state.anonymous)renderGuest(state.pendingCount);}catch{}}

async function api(path,options={}){let response;try{response=await fetch('/api/'+path,{...options,credentials:'same-origin'});}catch{throw new Error('目前無法連線，請檢查網路後重試。');}const data=await response.json();if(!response.ok){if(response.status===401&&!inviteToken){$('#connection-state').innerHTML='<a href="/signin-with-chatgpt?return_to=%2Fbank" target="_top">登入已到期，點此重新登入</a>';}throw new Error(data.error||'暫時無法完成，請稍後重試。');}return data;}
function showToast(message){clearTimeout(toastTimer);$('#toast-msg').textContent=message;$('#toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4500);}
function openModal(id){previousFocus=document.activeElement;document.querySelectorAll('[id^="modal-"]').forEach(m=>m.classList.add('hidden'));const m=document.getElementById(id);m.classList.remove('hidden');[...$('.bank-shell').children].forEach(el=>{el.inert=el!==m&&el.id!=='toast';});setTimeout(()=>m.querySelector('button,input,textarea,a')?.focus(),30);}
function closeModal(id){if(inviteToken&&id==='modal-web')return;if(id==='modal-web')stopRecording();document.getElementById(id).classList.add('hidden');[...$('.bank-shell').children].forEach(el=>el.inert=false);document.querySelectorAll('video').forEach(v=>v.pause());previousFocus?.focus();}
function drawQuote(){const list=profile?deposits.filter(d=>d.opened):starterQuotes;if(!list.length){showToast('先邀請朋友存入一份肯定，再拆開它吧。');return false;}let n=Math.floor(Math.random()*list.length);if(n===lastQuote&&list.length>1)n=(n+1)%list.length;lastQuote=n;const d=list[n];$('#withdraw-text').textContent=d.text||'朋友為你錄了一段加油，點下方播放。';$('#withdraw-author').textContent=`來自 ${d.author} 的肯定`;const video=$('#withdraw-video');video.hidden=!d.video;if(d.video)video.src=d.video;else video.removeAttribute('src');$('#withdraw-text').classList.remove('celebrate');requestAnimationFrame(()=>$('#withdraw-text').classList.add('celebrate'));return true;}
function openWithdrawModal(){if(drawQuote())openModal('modal-withdraw');}
function openWidgetModal(){refreshWidgetQuote();openModal('modal-widget');}
function refreshWidgetQuote(){const list=deposits.filter(d=>d.opened),d=list[Math.floor(Math.random()*list.length)];$('#widget-quote').replaceChildren();const p=document.createElement('p');p.textContent=d?(d.text||'朋友錄下了一段加油，回到存摺播放。'):'讓朋友存入第一份心意，下次低潮時，就能在這裡遇見溫暖。';const s=document.createElement('small');s.textContent=d?`— ${d.author}`:'桌面小工具外觀預覽';$('#widget-quote').append(p,s);}
function renderDeposits(){const list=$('#deposit-list');list.replaceChildren();if(!deposits.length){const p=document.createElement('p');p.className='deposit-card bank-note';p.textContent='存摺還是空白的。發起一張請款單，邀請一位信任的朋友，把他眼中的你存進來。';list.append(p);}deposits.forEach(d=>{const card=document.createElement('article');card.className='deposit-card';const meta=document.createElement('small');meta.textContent=new Date(d.date).toLocaleString('zh-TW',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});const p=document.createElement('p');p.textContent=d.opened?d.text:'有一份心意，正在等你親手拆開。';const author=document.createElement('small');author.textContent=`來自：${d.author}`;card.append(meta,p,author);if(!d.opened){const b=document.createElement('button');b.className='extra-button w-full mt-3';b.textContent='🎁 拆開這份心意';b.onclick=()=>openUnboxModal(d.id);card.append(b);}else if(d.video){const v=document.createElement('video');v.controls=true;v.playsInline=true;v.preload='metadata';v.src=d.video;card.append(v);}list.append(card);});document.querySelectorAll('[data-count]').forEach(el=>el.textContent=deposits.length);const unread=deposits.filter(d=>!d.opened).length;$('#notification-count').textContent=unread;$('#notification-count').hidden=!unread;$('#notification-button').setAttribute('aria-label',unread?`${unread} 份心意等待開箱`:'查看新存款');}
async function refreshDeposits(silent=false){try{const data=await api('deposits');const before=deposits.length;const changed=JSON.stringify(data.deposits)!==JSON.stringify(deposits);deposits=data.deposits;if(changed||!$('#deposit-list').children.length)renderDeposits();$('#connection-state').textContent='已連上你的雲端存摺';if(silent&&deposits.length>before)showToast('收到新的心意，點鈴鐺開箱 🎁');}catch(e){$('#connection-state').textContent=e.message;if(!silent)showToast(e.message);}}
function openUnboxModal(id){if(!profile){promptSignIn();return;}pending=deposits.find(d=>d.id===id)||deposits.find(d=>!d.opened);if(!pending){showToast('目前沒有待拆封的新存款。');return;}opened=false;$('#unbox-author').textContent=pending.author;$('#unbox-text').textContent='有一份給你的心意，等你親手打開。';$('#unbox-content').classList.add('gift-sealed');$('#unbox-action').textContent='🎁 拆開這份心意';$('#unbox-video').hidden=true;openModal('modal-unbox');}
async function unwrapGift(){if(!pending)return;if(!opened){opened=true;$('#unbox-text').textContent=pending.text||'朋友為你錄了一段加油。';$('#unbox-content').classList.remove('gift-sealed');$('#unbox-content').classList.add('celebrate');$('#unbox-video').hidden=!pending.video;if(pending.video)$('#unbox-video').src=pending.video;$('#unbox-action').textContent='💛 收進我的存摺';return;}$('#unbox-action').disabled=true;try{await api(`deposits/${pending.id}/open`,{method:'POST'});deposits=deposits.map(d=>d.id===pending.id?{...d,opened:true}:d);pending=null;renderDeposits();closeModal('modal-unbox');showToast('已收進你的雲端存摺 💛');}catch(e){showToast(e.message);}finally{$('#unbox-action').disabled=false;}}
function updateLink(){question=$('#custom-question').hidden?questions[Number($('#question-choices .selected-question')?.dataset.index||0)]:$('#custom-question').value.trim();const signature=JSON.stringify([$('#owner-name').value.trim(),question]);if(signature!==inviteSignature){inviteLink=null;$('#share-link').value='';}$('#share-link').placeholder='選好問題後，按下方建立連結';}
function openInvoiceModal(){updateLink();openModal('modal-invoice');}
async function copyLinkAndClose(){updateLink();const name=$('#owner-name').value.trim();if(!name||!question){showToast('請填寫你的稱呼與想問朋友的問題。');(!name?$('#owner-name'):$('#custom-question')).focus();return;}const b=$('#create-invite');b.disabled=true;b.textContent='正在準備請款單…';try{if(!inviteLink){const data=await api('invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,question})});inviteLink=data.url;inviteSignature=JSON.stringify([name,question]);if(!profile)$('#guest-invite-note').hidden=false;}$('#share-link').value=inviteLink;try{await navigator.clipboard.writeText(inviteLink);showToast('已複製！傳給朋友，邀請他存入心意 💌');}catch{$('#share-link').focus();$('#share-link').select();showToast('連結已建立，請長按或按 Ctrl+C 複製。');}}catch(e){showToast(e.message);}finally{b.disabled=false;b.textContent=inviteLink?'複製分享連結':'建立並複製分享連結';}}
function openWebPreviewModal(){previewMode=true;updateLink();$('#friend-heading').textContent=`為 ${$('#owner-name').value.trim()||'你的朋友'} 存入自信`;$('#friend-question').textContent=question||questions[0];$('#friend-success').hidden=true;$('#friend-form').hidden=false;$('#friend-note').textContent='這是填寫預覽，送出不會建立存款。實際收送請使用你開立的分享連結。';openModal('modal-web');}
async function submitFriendDeposit(event){event?.preventDefault();if(submitting)return;if(recorder?.state==='recording'||recordFinalizing){showToast('請先停止錄影並確認影片。');return;}const author=$('#friend-name').value.trim(),text=$('#friend-message').value.trim();if(!author){showToast('請留下你的稱呼。');$('#friend-name').focus();return;}if(!text&&!videoBlob){showToast('寫下一句鼓勵，或錄一段影片吧。');$('#friend-message').focus();return;}if(videoBlob?.size>25*1024*1024){showToast('影片超過 25 MB，請重錄較短的內容。');return;}const b=$('#send-deposit');submitting=true;b.disabled=true;b.textContent='正在送出，請稍候…';try{if(!previewMode){const form=new FormData();form.append('author',author);form.append('message',text);form.append('submissionId',submissionId);if(videoBlob)form.append('video',videoBlob,'encouragement.'+(videoBlob.type.includes('webm')?'webm':'mp4'));await api(`invites/${inviteToken}/deposits`,{method:'POST',body:form});}$('#friend-form').hidden=true;$('#friend-success').hidden=false;$('#success-title').textContent=previewMode?'預覽完成，這份心意很溫暖':'心意已存入，謝謝你';$('#success-description').textContent=previewMode?'這次是填寫預覽，沒有送出任何資料。建立分享連結後，朋友的心意就能真正入帳。':'你的留言與影片已存入對方的私人存摺，只有收件者登入後能查看。你可以安心關閉這個頁面。';$('#friend-name').value='';$('#friend-message').value='';clearVideo();submissionId=crypto.randomUUID();}catch(e){showToast(e.message);}finally{submitting=false;b.disabled=false;b.textContent='💌 存入朋友的自信銀行';}}

function stopRecording(){recordingRequest++;clearTimeout(recordTimer);clearInterval(recordTick);if(recorder&&recorder.state==='recording'){recordFinalizing=true;recorder.stop();}stream?.getTracks().forEach(t=>t.stop());stream=null;$('#record-button').textContent='🎥 錄製 15 秒加油影片';}
async function recordVideo(){if(recorder?.state==='recording'){stopRecording();return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){showToast('此瀏覽器不支援錄影，可使用下方選擇影片。');return;}const ticket=++recordingRequest;$('#record-button').disabled=true;try{const captured=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});if(ticket!==recordingRequest){captured.getTracks().forEach(t=>t.stop());return;}stream=captured;const v=$('#video-preview');v.hidden=false;v.srcObject=stream;v.muted=true;v.controls=false;await v.play();const chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{recordFinalizing=false;setVideo(new Blob(chunks,{type:recorder.mimeType}));};recorder.start();let seconds=15;$('#record-button').textContent=`停止錄影（剩 ${seconds} 秒）`;recordTick=setInterval(()=>{$('#record-button').textContent=`停止錄影（剩 ${--seconds} 秒）`;},1000);recordTimer=setTimeout(stopRecording,15000);}catch{stream?.getTracks().forEach(t=>t.stop());showToast('無法開啟相機，請允許相機與麥克風，或選擇現有影片。');}finally{$('#record-button').disabled=false;}}
function setVideo(blob){if(videoURL)URL.revokeObjectURL(videoURL);videoBlob=blob;videoURL=URL.createObjectURL(blob);const v=$('#video-preview');v.srcObject=null;v.src=videoURL;v.hidden=false;v.muted=false;v.controls=true;$('#remove-video').hidden=false;}
function clearVideo(){stopRecording();if(videoURL)URL.revokeObjectURL(videoURL);videoBlob=null;videoURL=null;const v=$('#video-preview');v.pause();v.srcObject=null;v.removeAttribute('src');v.hidden=true;$('#video-file').value='';$('#remove-video').hidden=true;}
document.querySelectorAll('[id^="modal-"]').forEach(m=>{m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.setAttribute('aria-label',m.querySelector('h3')?.textContent||'預覽');m.addEventListener('click',e=>{if(e.target===m&&m.id!=='modal-web')closeModal(m.id);});m.firstElementChild?.classList.add('modal-panel');});
document.addEventListener('keydown',e=>{const m=[...document.querySelectorAll('[id^="modal-"]')].find(m=>!m.classList.contains('hidden'));if(!m)return;if(e.key==='Escape'){closeModal(m.id);return;}if(e.key==='Tab'){const f=[...m.querySelectorAll('button,input,textarea,a[href],video[controls]')].filter(el=>!el.disabled&&el.getClientRects().length);if(!f.length)return;if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus();}}});
$('#question-choices').querySelectorAll('button').forEach((button,index)=>{button.dataset.index=index;button.addEventListener('click',()=>{$('#question-choices').querySelectorAll('button').forEach(b=>{b.classList.remove('selected-question');b.setAttribute('aria-pressed','false');});button.classList.add('selected-question');button.setAttribute('aria-pressed','true');$('#custom-question').hidden=index!==2;if(index===2)$('#custom-question').focus();updateLink();});});
$('#owner-name').addEventListener('input',updateLink);$('#custom-question').addEventListener('input',updateLink);$('#friend-form').addEventListener('submit',submitFriendDeposit);
$('#video-file').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('video/')||f.size>25*1024*1024){showToast('請選擇小於 25 MB 的影片。');e.target.value='';return;}const url=URL.createObjectURL(f),v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{URL.revokeObjectURL(url);if(!Number.isFinite(v.duration)||v.duration>15.5){showToast('請選擇 15 秒以內的影片。');e.target.value='';}else setVideo(f);};v.onerror=()=>{URL.revokeObjectURL(url);showToast('無法讀取這段影片，請換一個檔案。');e.target.value='';};v.src=url;});
$('#toast').setAttribute('role','status');$('#toast').setAttribute('aria-live','polite');document.querySelectorAll('button').forEach(b=>{if(!b.textContent.trim())b.setAttribute('aria-label',b.title||'關閉視窗');});

async function boot(){if(inviteToken){document.body.classList.add('friend-route');previewMode=false;openModal('modal-web');$('#friend-close').hidden=true;$('#friend-form').hidden=true;$('#friend-question').textContent='正在開啟請款單…';try{const data=await api('invites/'+inviteToken);$('#friend-heading').textContent='為 '+data.name+' 存入自信';$('#friend-question').textContent=data.question;$('#friend-form').hidden=false;$('#friend-note').textContent='你填寫的稱呼、留言及影片將傳給收件者，只有對方登入後能查看。請只留下你願意分享的內容。';}catch(e){$('#friend-question').textContent=e.message;$('#invite-retry').hidden=false;}}else{renderGuest();try{const state=await api('me');if(state.anonymous){profile=null;renderGuest(state.pendingCount);}else{profile=state;if(state.guest)await api('claim',{method:'POST'});$('#owner-name').value=(profile.name||'').slice(0,40);$('#account-name').textContent=profile.name||profile.email;$('#account-action').textContent='登出';$('#account-action').href='/signout-with-chatgpt?return_to=%2F';$('#bank-privacy-note').textContent='你的存摺只有你能查看。文字與影片皆儲存在雲端。';await refreshDeposits();if(new URL(location.href).searchParams.get('open')==='1')openUnboxModal();}}catch(e){$('#connection-state').textContent=e.message;}const refresh=()=>{if(!document.hidden){if(profile)refreshDeposits(true);else refreshGuest();}};setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);}}
boot();window.addEventListener('pagehide',stopRecording);
