import {DatabaseSync} from 'node:sqlite';
import {parseHTML} from 'linkedom';
import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
import {handleAPI} from './server/api.mjs';
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const DB={prepare(query){const statement=sql.prepare(query);let args=[];return{bind(...values){args=values;return this;},async first(){return statement.get(...args)||null;},async all(){return{results:statement.all(...args)};},async run(){return statement.run(...args);}};}};
DB.batch=async statements=>{sql.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}};
const files=new Map();const FILES={async put(key,body,options){files.set(key,{data:await new Response(body).arrayBuffer(),type:options.httpMetadata.contentType});},async delete(key){files.delete(key);},async get(key){const f=files.get(key);return f?{body:f.data,size:f.data.byteLength}:null;}};
const owner={userId:'owner-a',fullName:'小安',displayName:'小安',email:'a@example.test'},other={userId:'owner-b',displayName:'其他人',email:'b@example.test'};
const origin='https://confidence.example';
function request(path,{method='GET',body,headers={},user=owner}={}){if(method!=='GET')headers.Origin??=origin;return handleAPI(new Request(origin+'/api/'+path,{method,headers,body}),{DB,FILES},user);}
async function jsonReq(path,body,user=owner){return request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),user});}
assert.equal((await request('deposits',{user:null})).status,401);
assert.equal((await request('me',{user:null})).status,200);
const invite=await(await jsonReq('invites',{name:'小安',question:'一個優點？'})).json();assert.match(invite.id,/^[a-f0-9]{64}$/);
const publicInvite=await(await request('invites/'+invite.id,{user:null})).json();assert.equal(publicInvite.name,'小安');assert.equal(publicInvite.owner_id,undefined);
assert.equal((await request('invites/invalid',{user:null})).status,404);
const submissionId=crypto.randomUUID();
function form(message='你很棒',video=false,id=submissionId){const f=new FormData();f.append('author','小晴');f.append('message',message);f.append('submissionId',id);if(video)f.append('video',new Blob([new Uint8Array([0,0,0,16,102,116,121,112,105,115,111,109,0,0,0,0])],{type:'video/mp4'}),'test.mp4');return f;}
const submitted=await request(`invites/${invite.id}/deposits`,{method:'POST',body:form('<b>你很棒</b>',true),user:null});assert.equal(submitted.status,201);const deposit=await submitted.json();assert.equal(files.size,1);
const repeated=await request(`invites/${invite.id}/deposits`,{method:'POST',body:form(),user:null});assert.equal(repeated.status,200);assert.equal((await repeated.json()).id,deposit.id);
assert.equal((await(await request('deposits')).json()).deposits.length,1);
assert.equal((await(await request('deposits',{user:other})).json()).deposits.length,0);
assert.equal((await request(`deposits/${deposit.id}/video`,{user:other})).status,404);
assert.equal((await request(`deposits/${deposit.id}/video`,{user:null})).status,401);
assert.equal((await request(`deposits/${deposit.id}/video`)).status,200);
assert.equal((await request(`deposits/${deposit.id}/open`,{method:'POST',user:other})).status,404);
assert.equal((await request(`deposits/${deposit.id}/open`,{method:'POST',headers:{Origin:'https://attacker.example'}})).status,403);
assert.equal((await request(`deposits/${deposit.id}/open`,{method:'POST'})).status,200);
assert.equal((await request(`invites/${invite.id}/deposits`,{method:'POST',body:form('',false,crypto.randomUUID()),user:null})).status,400);
const fake=form('',false,crypto.randomUUID());fake.append('video',new Blob(['<html>bad</html>'],{type:'video/mp4'}),'fake.mp4');assert.equal((await request(`invites/${invite.id}/deposits`,{method:'POST',body:fake,user:null})).status,400);
sql.prepare('UPDATE invites SET expires_at = ? WHERE id = ?').run(0,invite.id);assert.equal((await request('invites/'+invite.id,{user:null})).status,410);sql.prepare('UPDATE invites SET expires_at = ? WHERE id = ?').run(Date.now()+86400000,invite.id);
const guestCreate=await jsonReq('invites',{name:'還沒登入的小安',question:'給我一句鼓勵'},null);assert.equal(guestCreate.status,201);const cookie=guestCreate.headers.get('set-cookie').split(';')[0];assert.match(guestCreate.headers.get('set-cookie'),/HttpOnly/);const guestInvite=await guestCreate.json();
const guestSent=await request(`invites/${guestInvite.id}/deposits`,{method:'POST',body:form('未登入先收到的心意',true,crypto.randomUUID()),user:null});assert.equal(guestSent.status,201);const guestDeposit=await guestSent.json();
const guestState=await(await request('me',{user:null,headers:{Cookie:cookie}})).json();assert.equal(guestState.pendingCount,1);assert.equal(guestState.deposits,undefined);
assert.equal((await request('deposits',{user:null,headers:{Cookie:cookie}})).status,401);assert.equal((await request('claim',{method:'POST',user:null,headers:{Cookie:cookie}})).status,401);
assert.equal((await request('claim',{method:'POST',user:other,headers:{Cookie:cookie}})).status,200);
assert.equal((await request(`deposits/${guestDeposit.id}/video`,{user:other})).status,200);assert.equal((await request(`deposits/${guestDeposit.id}/video`,{user:owner})).status,404);
await request('claim',{method:'POST',user:owner,headers:{Cookie:cookie}});assert.equal((await request(`deposits/${guestDeposit.id}/video`,{user:owner})).status,404);
const afterClaim=await request(`invites/${guestInvite.id}/deposits`,{method:'POST',body:form('登入後才送到的留言',false,crypto.randomUUID()),user:null});assert.equal(afterClaim.status,201);assert.equal((await(await request('deposits',{user:other})).json()).deposits.length,2);
const {window}=parseHTML(fs.readFileSync('index.html','utf8'));window.document.querySelectorAll('video').forEach(v=>v.pause=()=>{});
const context={document:window.document,window,URL,URLSearchParams,Blob,FormData,crypto,console,Math,Date,JSON,Number,Array,setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame:fn=>fn(),location:{href:origin+'/bank',pathname:'/bank'},navigator:{clipboard:{writeText:async()=>{}}},fetch:async(path,options={})=>request(path.replace('/api/',''),options)};
vm.createContext(context);vm.runInContext(fs.readFileSync('app.js','utf8').replace("boot();window.addEventListener", "window.addEventListener"),context);const run=s=>vm.runInContext(s,context),$=s=>window.document.querySelector(s);
await run('boot()');assert.equal($('#deposit-list').children.length,1);assert.equal($('#deposit-list b'),null);assert.match($('#deposit-list').textContent,/<b>你很棒<\/b>/);
run('openWithdrawModal()');assert.equal($('#withdraw-text').textContent,'<b>你很棒</b>');
run('openInvoiceModal()');$('#question-choices').children[1].click();await run('copyLinkAndClose()');assert.match($('#share-link').value,/\/ask\/[a-f0-9]{64}$/);
run('openWebPreviewModal()');await run('submitFriendDeposit()');assert.equal($('#friend-success').hidden,true);$('#friend-name').value='小晴';$('#friend-message').value='測試預覽';await run('submitFriendDeposit()');assert.equal($('#friend-success').hidden,false);assert.equal((await(await request('deposits')).json()).deposits.length,1);
for(const match of fs.readFileSync('app.js','utf8').matchAll(/\$\('(#[a-z-]+)'\)/g))assert.ok($(match[1]),`Missing ${match[1]}`);
window.document.querySelectorAll('video').forEach(v=>v.pause=()=>{});context.fetch=async(path,options={})=>request(path.replace('/api/',''),{...options,user:null});run('closeModal(\'modal-web\')');await run('boot()');assert.match($('#account-name').textContent,/不用急著登入/);run('openWithdrawModal()');assert.match($('#withdraw-author').textContent,/體驗卡/);run('closeModal(\'modal-withdraw\');openUnboxModal()');assert.equal($('#modal-signin').classList.contains('hidden'),false);
console.log('Passed: migrations, private accounts, anonymous invitations, cloud text/video storage, replay deduplication, owner-only video access, origin checks, expiration, file validation, safe rendering, and preview isolation.');sql.close();
